name: CI/CD Pipeline for ANN Classification

on:
  push:
    branches:
      - main  # Runs the workflow when you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Docker Image
        run: |
          docker build -t ann-classification:latest .

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ann-classification
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v2
        with:
          name: ann-classification
          path: .

      - name: Stop Old Container
        run: |
          docker stop ann-container || true
          docker rm ann-container || true

      - name: Run New Container
        run: |
          docker run -d -p 8501:8501 --name ann-container ann-classification:latest
